### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by polcak** [cervinka-zbynek/masters-thesis#1]
Dobrý den,

mohl byste prosím přidat k repozitáři licenci, aby se na práci mohlo dále stavět? Jde sice o školní dílo, takže škole některá práva náležejí ze zákona, ale bylo by lepší, kdyby tady licence uvedená byla. Inspirovat se můžete např. v mých repozitářích.

Děkuji,

Libor Polčák

**Comment by cervinka-zbynek** [comment]
Dobrý den,
licence byla přidána.

S pozdravem

Zbyněk Červinka

**Comment by polcak** [comment]
Díky.
